from pathlib import Path

DEFAULT_DATA_DIR = Path("data")
DEFAULT_IMAGES_DIR = DEFAULT_DATA_DIR / "Flickr8k_Dataset"
DEFAULT_CAPTIONS_FILE = DEFAULT_DATA_DIR / "Flickr8k_text" / "Flickr8k.token.txt"

DEFAULT_ARTIFACTS_DIR = Path("artifacts")
DEFAULT_FEATURES_FILE = DEFAULT_ARTIFACTS_DIR / "features.pkl"
DEFAULT_TOKENIZER_FILE = DEFAULT_ARTIFACTS_DIR / "tokenizer.pkl"
DEFAULT_MODEL_FILE = DEFAULT_ARTIFACTS_DIR / "caption_model.keras"
DEFAULT_HISTORY_FILE = DEFAULT_ARTIFACTS_DIR / "training_history.json"

DEFAULT_MAX_LENGTH = 34
DEFAULT_VOCAB_SIZE = 5000
IMAGE_SIZE = (224, 224)
